# Generated by Django 5.0 on 2024-01-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
