# Generated by Django 5.0 on 2024-01-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_category_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='amount',
            new_name='goal_amount',
        ),
        migrations.AddField(
            model_name='savings',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
