# Generated by Django 5.0 on 2024-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_amount_savings_goal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
