# Generated by Django 5.0 on 2024-02-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_income_category_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Savings', 'Savings'), ('Exchange', 'Exchange')], max_length=8),
        ),
    ]
