# Generated by Django 5.0 on 2024-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='categories',
            field=models.ManyToManyField(blank=True, to='wallet.category'),
        ),
    ]
