# Generated by Django 5.0 on 2024-02-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_expense_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction',
        ),
        migrations.AddField(
            model_name='income',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='wallet.transaction'),
        ),
    ]
