# Generated by Django 5.0 on 2024-02-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_remove_expense_transaction_income_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='wallet.transaction'),
        ),
    ]
