# Generated by Django 4.2.10 on 2024-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_alter_currency_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
